version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zms_pizza_backend
      MYSQL_USER: root1
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./zms-pizza-backend
      dockerfile: Dockerfile
    container_name: zms-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/zms_pizza_backend
      SPRING_DATASOURCE_USERNAME: root1
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

  frontend:
    build:
      context: ./zms-pizza-frontend
      dockerfile: Dockerfile
    container_name: zms-frontend
    ports:
      - "3000"
    depends_on:
      - backend

volumes:
  mariadb_data:
